name: macOS_arm64

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:
    branches: '*'

jobs:
  build:

    runs-on: macos-15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run GNU Make with GNU compiler
      run: |
        ./build_and_run.sh

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts_macOS_arm64
        path: ./
